name: CI-on-merge

on:
  release:
    types:
      - created

env:
  # Use docker.io for Docker Hub if empty
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.head_ref }}

jobs:
  build-and-push-to-registry:
    name: Build and Push image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v2
        name: Build and push Docker image latest
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          labels: |
            version=${{ github.event.release.tag_name }}
            ${{ steps.meta.outputs.labels }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PRIVATE_TOKEN_GITHUB }}
          build-args: |
            GIT_TOKEN=${{ secrets.PRIVATE_TOKEN_GITHUB}}
      - name: Send message to Teams channel
        run: |
          curl -H "Content-Type: application/json" -d '
          {
            "title": "${{ github.repository }} - Release ${{ github.event.release.tag_name }} is now available!",
            "text": "'"\n\n${{ github.event.release.body }}"'"
          }
          ' ${{ secrets.TEAMS_WEBHOOK_URL }}
